#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

"${DIR}/build-dns-image"
docker run -p 53:53/udp -p 53:53/tcp -t --rm --name dns demo/dns:0.1